baseURL = "https://zitanguyen.com/"
languageCode = "en-us"
title = "Zita Nguyen"
theme = "minimal"
disqusShortname = "znguyen" # delete this to disable disqus comments
googleAnalytics = ""

[params]
    author = "Calin Tataru"
    description = "My coding journals"
    githubUsername = "ZitaNguyen"
    accent = "#FDA50F"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/posts/"
    name = "Posts"
    weight = 3

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:zitanguyen84@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/ZitaNguyen"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.youtube.com/channel/UCuDJhg8PH-OvKTBvCdpmTLg?view_as=subscriber"
    name = "youtube"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/zitanguyen/"
    name = "linkedin"
    weight = 4

[[menu.icon]]
    url = "https://stackoverflow.com/users/11696515/zita-nguyen"
    name = "stack-overflow"
    weight = 5
